Booting/linux-bootstrap - 2, 3, 4, 5, 6 번역 완료 했습니다.
junsooo/linux-insides-ko pull request #43
Opened 2019-11-20 07:13 UTC by juyoung0520

2019-11-24 11:35 UTC, junsooo requested changes
간단히 리뷰 했습니다.

2019-11-24 11:35 UTC, junsooo commented on Initialization/linux-initialization-1.md
> +[kASLR](https://en.wikipedia.org/wiki/Address_space_layout_randomization#Linux)을 사용하도록 설정되었으므로 로드 된 'startup_64'루틴 주소가 컴파일 된 주소와 다를 수 있으므로 델타를 계산해야합니다. 다음 코드:
마지막 부분에 `델타를 다음 코드를 통해 계산해야 합니다.` 이런 느낌으로 고치는 것이 필요할 듯 합니다.

2019-11-24 12:27 UTC, junsooo commented
굉장히 많이 번역해주셨네요. 감사드립니다.

2019-12-11 14:10 UTC, juyoung0520 commented
번역 완료하고 충돌 해결 하였습니다. 머지 부탁 드려요!

2020-01-03 03:42 UTC, merged

2020-01-03 03:43 UTC, junsooo commented
정말 많이 해주셨네요 감사합니다. 머지했습니다